import React from 'react'
import { ScrollView, StyleSheet, Text, View } from 'react-native'
import MainHeader from '../../components/headers/MainHeader'
import SearchInput from '../../components/UI/inputs/SearchInput'
import globalStyle from '../../constants/globalStyle'
import Box from '../../components/UI/Box'
import StatisticsCard from '../../components/cards/StatisticsCard'

const TermsAndConditionsScreen = (props) => {
    return (
        <View style={globalStyle.container}>

            <MainHeader navigation={props.navigation} />
            <SearchInput />

            <ScrollView style={{ backgroundColor: '#fff', paddingHorizontal: 20 }}>

                <Text style={globalStyle.textBold}>Terms and Conditions</Text>

                <Text style={styles.head}>1. Terms and Conditions use of this platform</Text>
                <Text style={styles.description}>1.1. Any person who access and/or use the Platform in any manner (referred as ”you”, “your”), shall be subject to these terms and conditions for use and be bound by the policies formulated by Reliance</Text>
                <Text style={styles.description}>1.2. These terms and conditions for use, the policies as list above, and such other policies or terms as may be prescribed by Reliance (“Terms”), together constitute a legally binding agreement between the You and Reliance, in connection with the access to or use of the Platform. You are requested to read these Terms carefully before accessing or using the Platform.</Text>
                <Text style={styles.description}>1.3. Reliance may update/modify/amend these Terms (including any portion of it) at any time, with or without advance notice.</Text>
                <Text style={styles.description}>1.4. Using the Services or accessing the Platform constitute your consent to the Terms. By using the Platform, the you signify your acceptance of these Terms and agrees to be legally bound by them. If at any time, you do not agree or wish to be bound by these Terms, you may not access use the Platform. These Terms supersede all previous terms and conditions communicated to you by Reliance, for the use of the Platform and all rights and liabilities of Reliance with respect to any Services to be provided will be limited to the scope of these Terms.</Text>
                <Text style={styles.description}>1.5. This document is an electronic record in terms of the Information Technology Act, 2000 (“IT Act”) and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the IT Act. This electronic record is generated by a computer system and does not require any physical or digital signatures.</Text>
                <Text style={styles.description}>1.6. In addition to these Terms, you may be required to comply with the terms and conditions of the third parties, whose links are contained/embedded in the Services. It is hereby clarified that Reliance shall not be held liable for any transaction between the User and any such third parties.</Text>

                <Text style={styles.head}>2. Registration</Text>
                <Text style={styles.description}>2.1 Registration. In order to avail the Services you will be required to register on the Platform. Registration is a one-time process and is free of cost. You may register in one of the following ways:</Text>
                <Text style={styles.description}>2.1.1 By creating an Ajio account: by providing the relevant information for the creation of your account on the Platform. Following this, an account with an exclusive user name and password (basis your inputs) will be created by Reliance for you.</Text>
                <Text style={styles.description}>2.1.2 By using a third-party account: you may use the login credentials of the account maintained by the User with a Reliance-integrated third-party (illustratively, Google or Facebook), in which case you will also be subject to relevant third-party terms and conditions applicable to such account.</Text>

                <Text style={styles.description}>2. USER WARRANTIES AND RESTRICTIONS</Text>
                <Text style={styles.description}>2.1 You may use the Platform for reasonable and lawful purposes only, and shall not indulge in any activity that is unlawful or harmful to the Platform or its content. You are provided with a limited license to access and use the Platform, solely for the purpose of availing the Services, subject to these Terms.</Text>
                <Text style={styles.description}>2.2 You will not:</Text>
                <Text style={styles.description}>2.2.1 Delete or modify any content on the Platform, including but not limited to, any information regarding the Services, their performance, sales or pricing, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that the you do not own or have express permission to modify;</Text>
                <Text style={styles.description}>2.2.2 Decompile, reverse engineer, or disassemble the content;</Text>
                <Text style={styles.description}>2.2.3 Use the Services in any way that is unlawful, or harms Reliance or any other person or entity, as determined in Reliance’s sole discretion;</Text>
                <Text style={styles.description}>2.2.4 Using any engine, software, tool, agent or other mechanism (such as spiders, robots, avatars, worms, time bombs, Easter eggs, cancel bots, intelligent agents, etc.) to navigate or search the Platforms;</Text>
                <Text style={styles.description}>2.2.5 Make false or malicious statements against the Services, the Platform or Reliance;</Text>
                <Text style={styles.description}>2.2.6 Post, copy, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise impair or damage the Platform and/or Services or any connected network, or otherwise interfere with any person or entity's use or enjoyment of the Platform and/or the Services;</Text>
                <Text style={styles.description}>2.2.7 Engage in any form of antisocial, disruptive, or destructive acts, including “flaming,” “spamming,” “flooding,” “trolling,”, “phishing” and “griefing” as those terms are commonly understood and used on the internet; or</Text>
                <Text style={styles.description}>2.2.8 Post or upload any content that is libelous, defamatory, abusive, threatening, harassing, hateful, and offensive or otherwise violates any law or right of any third-party.</Text>
                <Text style={styles.description}>2.3 Do not host, display, upload, modify, publish, transmit, update or share on or through the Platform, any information that:</Text>
                <Text style={styles.description}>2.3.1 belongs to another person and to which they do not have any right;</Text>
                <Text style={styles.description}>2.3.2 is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise harmful in any manner whatsoever;</Text>
                <Text style={styles.description}>2.3.3 harms minors in any way;</Text>
                <Text style={styles.description}>2.3.4 infringes any patent, trademark, copyright or other proprietary rights;</Text>
                <Text style={styles.description}>2.3.5 violates any law for the time being in force;</Text>
                <Text style={styles.description}>2.3.6 deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</Text>
                <Text style={styles.description}>2.3.7 impersonates or defames another person; or</Text>
                <Text style={styles.description}>2.3.8 contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource.</Text>
                <Text style={styles.description}>2.4 You are solely responsible for maintaining the confidentiality of your Account Information and for restricting access to your computer or mobile or other similar device to prevent unauthorized access to their account. You are requested to safeguard your password and your account and make sure that others do not have access to it. It is the you responsibility to keep your Account Information current and accurate. You agree to: (a) immediately notify Reliance of any unauthorized use of the account or any other security breach; and (b) ensure that they exit from their account at the end of each session. Reliance will not be liable for any loss or direct or indirect damage arising from the User’s failure to comply with these conditions. You may be held liable for any losses incurred to Reliance or any other user due to unauthorized use of your account, resulting from the failure to keep your Account Information secure and confidential.</Text>
                <Text style={styles.description}>2.5 You will not be involved in the transmission of sensitive and personal information, including but not limited to Account Information (collectively “SPI”), which falls within the ambit of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, while accessing or using the Platform.</Text>
                <Text style={styles.description}>2.6 You represent and warrant to Reliance that: (a) you are 18 (eighteen) years of age or older; (b) your use of the Platform and/or Services will not violate any applicable law or regulation; and (c) all information that is submitted to Reliance in connection with the Platform and/or Services is true and accurate.</Text>

                <Text style={styles.head}>3. Content on Platform</Text>
                <Text style={styles.description}>3.1 All information, content and material contained on the Platform are and continue to be Reliance’s or relevant third party intellectual property. Further, all trademarks, services marks, trade names and trade secrets in relation to the Platform whether or not displayed on the Platform, are proprietary to Reliance or relevant third party. No information, content or material from the Platform may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way without our express written permission. Any unauthorized use terminates the permissions granted in these Terms.</Text>
                <Text style={styles.description}>3.2 The contents of Services, information, text, graphics, images, logos, button icons, software code, interface, design and the collection, arrangement and assembly of the content on the Platforms or any of the other Services are the property of Reliance or its affiliates or relevant third party (“Content”), and are protected under copyright, trademark and other applicable laws. The User shall not modify the Content or reproduce, display, publicly perform, distribute, reverse engineer or otherwise use the Content in any way for any public or commercial purpose or for personal gain.</Text>
                <Text style={styles.description}>3.3 Reliance authorises you to view and access Content solely for identifying Products, carrying out purchases of Products and processing returns and refunds, in accordance with Return and Refund Policy. Reliance, therefore, grants to you a limited, revocable license to access and use the Services. This license does not include a permission for carrying out any resale of the Products or commercial use of the Content, any collection and use of product listings, description, or prices, and, any derivative use of the Platforms or of Content.</Text>
                <Text style={styles.description}>3.4 You hereby grant to Reliance a royalty-free, perpetual, irrevocable, non-exclusive right and license to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from, display worldwide, or act on any material, review, feedback, comments etc., posted by you on the Platform without additional approval or consideration in any form, media, or technology now known or later developed, for the full term of any rights that may exist in such content, and the you waive any claim to the contrary over all feedback, comments, ideas or suggestions or any other content provided by them to Reliance through the Platform.</Text>

                <Text style={styles.head}>4. Manner of use of Platform</Text>
                <Text style={styles.description}>4.1 Display of Products for purchase on the Platforms is merely an invitation to offer. An order placed by you for purchase of a Product constitutes an offer. All orders placed by you on the Platforms are subject to the availability of such Product, Reliance’s acceptance of you offer and your continued adherence to these Terms. You acknowledge and undertake that you are accessing the Services provided on the Platform and are transacting at your own risk and are using your best judgment before entering into any transactions through the Platform. You may place the orders on the Platform for the products and at the price indicated therein.</Text>
                <Text style={styles.description}>4.2 You agree and acknowledge that you will have to make the requisite payment for the Services availed by them on the Platform. Reliance accepts online payments using either credit card, debit card, net banking, digital wallets or other payment options as made available by the Platform from time to time. The payments made by you through the Platform for the purchase of the Products, is subject to the Fees and Payment Policy.</Text>
                <Text style={styles.description}>4.3 Upon payment of the consideration for the Products or undertaking to pay for the Product (in case of cash on delivery), the Product shall be delivered to you, in accordance with the Delivery Policy.</Text>
                <Text style={styles.description}>4.4 All information in relation to third parties, including sellers and the Products as available on the Platforms (“Third Party Information”) are provided solely for reference. Reliance is not endorsing the Third Party Information and is not responsible for any errors and representation nor is it associated with it and you access the Third Party Information at the your own risk.</Text>
                <Text style={styles.description}>4.5 If you may cancel any order made on the Platform, return the Products purchased on the Platform as per Cancellation, Returns and Refund Policy.</Text>

                <Text style={styles.head}>5. Disclaimer of Warranties</Text>
                <Text style={styles.description}>5.1 Reliance will try to make access to and use of the Platform error-free. However, your access to the Platform may be suspended or restricted to allow for repairs, maintenance, or for introduction of new facilities or services. Please note that Reliance does not take responsibility for any access or use problems that arise from internet related issues at your end. Reliance reserves at all times, the right, at its sole discretion, to refuse access to the Platform, terminate accounts, remove or edit content at its discretion.</Text>
                <Text style={styles.description}>5.2 The Platform may contain user generated content which Reliance does not pre-screen and which contains views that may be opinions of users and also of experts. Reliance does not claim any ownership rights to the text, files, images including photos, videos, sounds, musical works or any user generated content that you may submit or publish on the Platform. After posting any UGC on the Platform, you continue to own the rights that they may have in that UGC, subject to the limited license set out herein below. Reliance will do its best to monitor, edit or remove such user generated content where it considers it appropriate or necessary to do so. Reliance does not promise that any user generated content on the Platform is accurate, complete or updated, that it will not offend or upset any person or that it does not infringe the intellectual property rights of third parties.</Text>
                <Text style={styles.description}>5.3 As a means to assist you in identifying the Products of your choice, Reliance provides visual representations on the Platforms including graphics, illustrations, photographs, images, videos, charts, screenshots, infographics and other visual aids. While reasonable efforts are made to provide accurate visual representations, Reliance disclaims any guarantee or warranty of exactness of such visual representation or description of the Product, with the actual Product ultimately delivered to you. The appearance of the Product when delivered may vary for various reasons.</Text>
                <Text style={styles.description}>5.4 The Services included on or otherwise made available to you through the Platforms are provided on an “as is” and “as available” basis without any representations or warranties, express or implied, except if otherwise specified in writing. Reliance does not covenant or warrant that:</Text>
                <Text style={styles.description}>5.4.1 the Services will be made available at all times;</Text>
                <Text style={styles.description}>5.4.2 the operation of the Platform, including the functions contained in any content, information and materials on the Platform or any third-party sites or services linked to the Platform will be uninterrupted, timely or error-free, that the defects will be rectified, or that the Platform or the servers that make such content, information and materials available are free of viruses or other harmful components</Text>
                <Text style={styles.description}>5.4.3 the Content available on the Platforms is complete, true, accurate or non-misleading; and</Text>
                <Text style={styles.description}>5.4.4 the Products are of specified merchantability, merchantable quality and fit for use for a particular purpose.</Text>

                <Text style={styles.head}>6. Indemnification and limitation of liability</Text>
                <Text style={styles.description}>6.1 You agree to indemnify, defend and hold harmless Reliance, its affiliates, officers, directors, employees, consultants, licensors, agents, and representatives from and against any and all third- party claims, losses, liabilities, damages, and/or costs (including reasonable attorney fees and costs) arising from the your access to or use of the Platform or the Services, violation of these Terms, or infringement of any intellectual property or other rights of Reliance or any third-party. Reliance will notify the you promptly of any such claim, loss, liability, or demand, and in addition to the foregoing, you agree to provide Reliance with reasonable assistance, at their expense, in defending any such claim, loss, liability, damage, or cost.</Text>
                <Text style={styles.description}>6.2 To the fullest extent permitted by law, in no event shall Reliance or any of its directors, officers, employees, agents or content or service providers (collectively, the “Reliance Representatives”) be liable to you for any direct, indirect, special, incidental, consequential, exemplary, special, remote or punitive damage, including, but not limited to damages for loss of profits, goodwill, use, data or other intangible losses arising from, or directly or indirectly related to, the use of, or the inability to use, the Platform or the content, materials and functions related thereto, the Services, provision of information via the Platform, lost business, even if such Reliance Representatives have been advised of the possibility of such damages.</Text>
                <Text style={styles.description}>6.3 In no event shall Reliance Representatives be liable for:</Text>
                <Text style={styles.description}>6.3.1 the use or inability to use the Platform and/or the Services;</Text>
                <Text style={styles.description}>6.3.2 any content posted, transmitted, exchanged or received by or on behalf of any user or other person on or through the Platform;</Text>
                <Text style={styles.description}>6.3.3 any unauthorized access to or alteration or transmissions of SPI or other user data; or</Text>
                <Text style={styles.description}>6.3.4 any other matter relating to the Platform or the Services.</Text>
                <Text style={styles.description}>6.4 Reliance is neither liable nor responsible for any actions or inactions of the other users of the Platform or any breach of conditions, representations or warranties by them. Reliance is not obligated to mediate or resolve any dispute or disagreement amongst two or more users of the Platform.</Text>
                <Text style={styles.description}>6.5 None of the directors, officials or employees of Reliance shall be personally liable for any action in connection with the Platform or the Services.</Text>

                <Text style={styles.head}>7. Access Outside the Republic of India.</Text>
                <Text style={styles.description}>7.1 Reliance makes no representation that the content on the Platform is appropriate to be used or accessed outside the Republic of India. Your use or access the Platform from outside the Republic of India, do so at their own risk and are responsible for compliance with the laws of such jurisdiction. These Terms do not constitute, nor may these Terms be used for or in connection with any promotional activities or solicitation by anyone in any jurisdiction in which such promotional activities or solicitation are not authorized or to any person to whom it is unlawful to promote or solicit.</Text>

                <Text style={styles.head}>8. Communication and Unsubscription</Text>
                <Text style={styles.description}>You hereby understands that with your registration onto the Platform, you may receive notifications from Reliance in the form of SMS messages on their registered mobile number or e-mails. These notifications could relate to their registration, transactions that they carry out through the Platform and/or promotions. Further, Reliance may also send notifications and reminders to them with respect to their activity on the Platform, in relation to the Services. Please note that while Reliance endeavors to provide these notifications and reminders to you, Reliance does not provide any guarantee and shall not be held liable or responsible for any failure to send such notifications or reminders to you. The User can unsubscribe / opt-out from receiving communications, newsletters and other notifications from Reliance at any time by following the procedure set forth on the Platform.</Text>

                <Text style={styles.head}>9. Term and Termination</Text>
                <Text style={styles.description}>9.1 These Terms shall be effective from the date of their publication on the Platform.</Text>
                <Text style={styles.description}>9.2 Reliance reserves the right to suspend or terminate its Services in the event of breach of any terms contained in these Terms, misrepresentation of information, any unlawful activity by you or if Reliance is unable to verify or authenticate any information submitted by you.</Text>
                <Text style={styles.description}>9.3 You may terminate the Agreement at any time by discontinuing the use of the Platforms or Services. By terminating the usage or the Agreement you will be obligated to pay for a Product purchased on the Platforms, or any other obligation which has accrued, or is unfulfilled and relates to the period, prior to termination.</Text>

                <Text style={styles.head}>10. Force Majeure</Text>
                <Text style={styles.description}>10.1 Reliance will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond Reliance’s reasonable control.</Text>

                <Text style={styles.head}>11. Waiver</Text>
                <Text style={styles.description}>11.1 No provision in these Terms will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by Reliance. Any consent by Reliance to, or waiver of a breach by the User, whether expressed or implied, will not constitute consent to, waiver of, or excuse for any other different or subsequent breach.</Text>

                <Text style={styles.head}>12. Severability</Text>
                <Text style={styles.description}>12.1 If any provision of these Terms is held by a court of competent jurisdiction to be unenforceable under applicable law, then such provision will be excluded from these Terms and the remainder of these Terms will be interpreted as if such provision were so excluded and will be enforceable in accordance with its terms; provided however that, in such event, these Terms will be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction.</Text>

                <Text style={styles.head}>13. Grievance Redressal</Text>
                <Text style={styles.description}>13.1 The User may submit any grievance with respect to the Platform or the Services, including with respect to any abuse on the Platform, including any discrepancies or grievances with respect to processing of information, to the Grievance Officer at:</Text>

                <Text style={styles.head}>14. Governing Law and Dispute Resolution</Text>
                <Text style={styles.description}>14.1 These Terms, all transactions consummated between you and Reliance and the relationship between you and Reliance is governed by the laws of India, without reference to any conflict of laws principles and with an exclusive jurisdiction to the courts of Mumbai.</Text>

                <Box height={20} />
                <StatisticsCard />
                <Box height={20} />

            </ScrollView>


        </View>
    )
}

export default TermsAndConditionsScreen

const styles = StyleSheet.create({
    head: {
        fontFamily: 'Montserrat-Bold',
        fontSize: 12,
        color: '#000',
        marginBottom: 10
    },
    description: {
        fontFamily: 'Montserrat-Regular',
        color: '#000',
        fontSize: 12,
        marginBottom: 20
    },
})
